/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pe.edu.upeu.app.components;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import pe.edu.upeu.app.util.UtilsX;

/**
 *
 * @author LABORATORIO_2
 */
public class ToastMsg extends javax.swing.JPanel {

    private static BufferedImage icono = null;
    private static BufferedImage iconoError = null;
    static Image scaleImage=null;
    static Image scaleImage2=null;
    UtilsX obj = new UtilsX();

    public ToastMsg() {
        initComponents();
        try {
               icono = ImageIO.read(obj.getFile("success.png"));
               scaleImage= icono.getScaledInstance(32, 32, Image.SCALE_AREA_AVERAGING);
               
                iconoError =ImageIO.read(obj.getFile("error.png"));
               scaleImage2= iconoError.getScaledInstance(32,32, Image.SCALE_AREA_AVERAGING);
        } catch (Exception e) {
            System.out.println("Error :"+e.getMessage());
        }
              
       
    }

    public static void error(String msgText) {
        ToastMsg.error(msgText, false);
    }

    public static void error(String msgText, boolean type) {
        msg.setText(msgText);
        msg.setForeground(new java.awt.Color(255, 0, 0));
        if (type) {
            jLabel1.setIcon(new ImageIcon(scaleImage2));
            msgPanel.setBackground(Color.BLACK);
        } else {
            jLabel1.setIcon(new ImageIcon(scaleImage2));
            msgPanel.setBackground(Color.WHITE);
        }
    }

    public static void success(String msgText) {
        jLabel1.setIcon(new ImageIcon(scaleImage));
        msg.setText(msgText);
        msg.setForeground(new java.awt.Color(0, 0, 100));
        msgPanel.setBackground(Color.WHITE
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();

        jLabel1.setMaximumSize(new java.awt.Dimension(140, 120));
        jLabel1.setPreferredSize(new java.awt.Dimension(32, 32));

        javax.swing.GroupLayout msgPanelLayout = new javax.swing.GroupLayout(msgPanel);
        msgPanel.setLayout(msgPanelLayout);
        msgPanelLayout.setHorizontalGroup(
            msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(msgPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        msgPanelLayout.setVerticalGroup(
            msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(msg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(msgPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(msgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(msgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel msg;
    private static javax.swing.JPanel msgPanel;
    // End of variables declaration//GEN-END:variables
}
